language: node_js
node_js:
  - "4.3.1"

after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly tests -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage